name: "test"

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  test:
    name: "Node ${{matrix.node-version}}"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "${{matrix.node-version}}"
          cache: "npm"
      - run: "npm install --frozen-lockfile"
      - run: "npm run lint"
      - run: "npx prettier -c src/"
      - run: "npm run test"
      - run: "npm run build"
      - run: "npx bob check"
