name: "test"

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  test:
    name: "Node ${{matrix.node-version}}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16, 18, 20]
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "${{matrix.node-version}}"
          cache: "yarn"
      - run: "yarn install --frozen-lockfile"
      - run: "yarn lint"
      - run: "yarn prettier -c src/"
      - run: "yarn test"
      - run: "yarn build"
